"""
מרענן את הסעיף האוטומטי ב-CLAUDE.md מתוך הקוד עצמו — בלי לייבא מודולים
(קריאת AST בלבד, כדי שלא יהיו תופעות לוואי). מעדכן רק את הבלוק שבין
AUTO:BEGIN ל-AUTO:END. הנרטיב הידני נשאר ללא נגיעה.

הרצה:  python docgen.py
רץ אוטומטית בכל ריצת "Daily Report" בענן.
"""
from __future__ import annotations

import ast
import datetime
import glob
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BEGIN = "<!-- AUTO:BEGIN"
END = "<!-- AUTO:END -->"


def _module_docline(path: str) -> str:
    """שורת התקציר הראשונה מה-docstring של המודול (ללא ייבוא)."""
    try:
        tree = ast.parse(Path(path).read_text(encoding="utf-8"))
        doc = (ast.get_docstring(tree) or "").strip()
        return doc.splitlines()[0].strip() if doc else ""
    except Exception:  # noqa: BLE001
        return ""


def build_block() -> str:
    py = sorted(p for p in glob.glob(str(ROOT / "*.py"))
                if Path(p).name != "docgen.py")
    out = [f"{BEGIN} — generated by `python docgen.py`; do not edit by hand -->",
           f"_Auto-updated: {datetime.date.today().isoformat()}_", ""]
    out.append(f"**Modules ({len(py)}):**")
    for p in py:
        out.append(f"- `{Path(p).name}` — {_module_docline(p)}")

    data = sorted(Path(x).name for x in glob.glob(str(ROOT / "data" / "*.json")))
    out += ["", "**Data files:** " + (", ".join(f"`{d}`" for d in data) or "—")]

    wfs = []
    for w in sorted(glob.glob(str(ROOT / ".github" / "workflows" / "*.yml"))):
        txt = Path(w).read_text(encoding="utf-8")
        crons = re.findall(r'cron:\s*"([^"]+)"', txt)
        cron_s = ", ".join(f"`{c}`" for c in crons) if crons else "dispatch only"
        wfs.append(f"`{Path(w).name}` ({cron_s})")
    out.append("**Workflows:** " + ("; ".join(wfs) or "—"))

    tcount = sum(
        len(re.findall(r"^def test_", Path(t).read_text(encoding="utf-8"), re.M))
        for t in glob.glob(str(ROOT / "tests" / "*.py"))
    )
    out += [f"**Tests:** {tcount}", END]
    return "\n".join(out)


def main() -> bool:
    md_path = ROOT / "CLAUDE.md"
    md = md_path.read_text(encoding="utf-8")
    block = build_block()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(md):
        new_md = pattern.sub(lambda _: block, md)
    else:
        new_md = md.rstrip() + "\n\n## Project inventory (auto-generated)\n" + block + "\n"
    if new_md != md:
        md_path.write_text(new_md, encoding="utf-8")
        print("CLAUDE.md auto-section updated")
        return True
    print("CLAUDE.md already up to date")
    return False


if __name__ == "__main__":
    main()
